In [8]:
# Qa

import numpy as np

y = np.array([1,2,3,4]) # NOTE:  you'll need this later

print(f"{np.array([[1,2,3], [4,2,1], [3,8,5], [-9,-1,0]])}")

[[ 1  2  3]
 [ 4  2  1]
 [ 3  8  5]
 [-9 -1  0]]


In [9]:
#### Qb Implement the $\norm{1}$ and $\norm{2}$ norms for vectors in python.

from math import fabs

def L1(x):
     return np.sum(np.abs(x))

def L2(x):
    return (np.sum(x*x))**0.5

def L2Dot(x):
    return np.sqrt(x.dot(x))

# TEST vectors: here I test your implementation...calling your L1() and L2() functions
tx=np.array([1, 2, 3, -1])
ty=np.array([3,-1, 4,  1])

expected_d1=8.0
expected_d2=4.242640687119285

d1=L1(tx-ty)

d2=L2(tx-ty)

print(f"tx-ty={tx-ty}, d1-expected_d1={d1-expected_d1}, d2-expected_d2={d2-expected_d2}")

eps=1E-9 # remember to import math for fabs
assert fabs(d1-expected_d1)<eps, "L1 dist seems to be wrong" 
assert fabs(d2-expected_d2)<eps, "L2 dist seems to be wrong" 

# comment-in once your L2Dot fun is ready...
d2dot=L2Dot(tx-ty)
print("d2dot-expected_d2=",d2dot-expected_d2)
assert fabs(d2dot-expected_d2)<eps, "L2Ddot dist seem to be wrong" 

tx-ty=[-2  3 -1 -2], d1-expected_d1=0.0, d2-expected_d2=0.0
d2dot-expected_d2= 0.0
