Defs
$$
    \newcommand\rem[1]{}
    \rem{ITMAL: CEF def and LaTeX commands, remember: no newlines in defs}
    \newcommand\eq[2]{#1 &=& #2\\}
    \newcommand\ar[2]{\begin{array}{#1}#2\end{array}}
    \newcommand\ac[2]{\left[\ar{#1}{#2}\right]}
    \newcommand\st[1]{_{\scriptsize #1}}
    \newcommand\norm[1]{{\cal L}_{#1}}
    \newcommand\obs[2]{#1_{\mbox{\scriptsize obs}}^{\left(#2\right)}}
    \newcommand\diff[1]{\mbox{d}#1}
    \newcommand\pown[1]{^{(#1)}}
    \def\pownn{\pown{n}}
    \def\powni{\pown{i}}
    \def\powtest{\pown{\mbox{\scriptsize test}}}
    \def\powtrain{\pown{\mbox{\scriptsize train}}}
    \def\bX{\mathbf{M}}
    \def\bX{\mathbf{X}}
    \def\bZ{\mathbf{Z}}
    \def\bw{\mathbf{m}}
    \def\bx{\mathbf{x}}
    \def\by{\mathbf{y}}
    \def\bz{\mathbf{z}}
    \def\bw{\mathbf{w}}
    \def\btheta{{\boldsymbol\theta}}
    \def\bSigma{{\boldsymbol\Sigma}}
    \def\half{\frac{1}{2}}
$$

In [2]:
# Qa

import numpy as np

y = np.array([1,2,3,4])

x = np.array([[1,2,3], [4,2,1], [3,8,5], [-9,-1,0]])

print(f"{np.array([[1,2,3], [4,2,1], [3,8,5], [-9,-1,0]])}")

[[ 1  2  3]
 [ 4  2  1]
 [ 3  8  5]
 [-9 -1  0]]


In [3]:
#### Qb Implement the L1 and L2 norms for vectors in python.

from math import fabs

def L1(x):
     return np.sum(np.abs(x))

def L2(x):
    return (np.sum(x*x))**0.5

def L2Dot(x):
    return np.sqrt(x.dot(x))

# TEST vectors: here I test your implementation...calling your L1() and L2() functions
tx=np.array([1, 2, 3, -1])
ty=np.array([3,-1, 4,  1])

expected_d1=8.0
expected_d2=4.242640687119285

d1=L1(tx-ty)

d2=L2(tx-ty)

print(f"tx-ty={tx-ty}, d1-expected_d1={d1-expected_d1}, d2-expected_d2={d2-expected_d2}")

eps=1E-9 # remember to import math for fabs
assert fabs(d1-expected_d1)<eps, "L1 dist seems to be wrong" 
assert fabs(d2-expected_d2)<eps, "L2 dist seems to be wrong" 

# comment-in once your L2Dot fun is ready...
d2dot=L2Dot(tx-ty)
print("d2dot-expected_d2=",d2dot-expected_d2)
assert fabs(d2dot-expected_d2)<eps, "L2Ddot dist seem to be wrong" 

tx-ty=[-2  3 -1 -2], d1-expected_d1=0.0, d2-expected_d2=0.0
d2dot-expected_d2= 0.0


In [8]:
# TODO: solve Qc...implement your RMSE function here


def RMSE(y_pred,y_true):
     return 1/2 * L2Dot(y_pred - y_true)



# Dummy h function:
def h(X):    
    if X.ndim!=2:
        raise ValueError("excpeted X to be of ndim=2, got ndim=",X.ndim)
    if X.shape[0]==0 or X.shape[1]==0:
        raise ValueError("X got zero data along the 0/1 axis, cannot continue")
    return X[:,0]

# Calls your RMSE() function:
r=RMSE(h(x),y)

# TEST vector:
eps=1E-9
expected=6.57647321898295
print(f"RMSE={r}, diff={r-expected}")
assert fabs(r-expected)<eps, "your RMSE dist seems to be wrong" 

RMSE=6.576473218982953, diff=2.6645352591003757e-15


In [19]:
def MAE(x,y):
    return 1/len(y)*(L1(x - y))

# Calls your MAE function:
r=MAE(h(x), y)

# TEST vector:
expected=3.75
print(f"MAE={r}, diff={r-expected}")
assert fabs(r-expected)<eps, "MAE dist seems to be wrong" 

MAE=3.75, diff=0.0


In [36]:
# Pythonic code:
import numbers

def L1(x):
    if not (x.ndim == 1):
        raise Exception("Faulty input dimensions for L1")
    result = np.sum(np.abs(x))
    if not isinstance(result,Number):
        raise Exception("L1 return val was not a number")
    return result 

def L2(x):
    if not (x.ndim == 1):
        raise Exception("Faulty input dimensions for L2")
    result = (np.sum(x*x))**0.5
    if not isinstance(result,Number):
        raise Exception("L2 return val was not a number")
    return result 

def L2Dot(x):
    if not (x.ndim == 1):
        raise Exception("Faulty input dimensions for L2Dot")
    result = np.sqrt(x.dot(x))
    if not isinstance(result,numbers.Number):
        raise Exception("L2Dot return val was not a number")
    return result 

def RMSE(y_pred,y_true):
    if not (y_pred.ndim == 1 and y_true.ndim == 1 and y_pred.shape == y_true.shape):
        raise Exception("Faulty input dimensions for RMSE")
    result = 1/2 * L2Dot(y_pred - y_true)
    if not isinstance(result,numbers.Number):
        raise Exception("RMSE return val was not a number")
    return result 

def MAE(y_pred,y_true):
    if not (y_pred.ndim == 1 and y_true.ndim == 1 and y_pred.shape == y_true.shape):
        raise Exception("Faulty input dimensions for MAE")
    result =  1/len(y)*(L1(x - y))
    if not isinstance(result,numbers.Number):
        raise Exception("MAE return val was not a number")
    return result 



In [37]:
multi_dimensional = np.array([[1,2,3], [4,2,1], [3,8,5], [-9,-1,0]])
len_4_a = np.array([1, 1, 3, -1])
len_4_b = np.array([1, 2, 2, 7])
len_5 = np.array([1, 2, 3, -1, 5])


try:
    L1(multi_dimensional)
except Exception as e:
    print(e)

try:
    L2Dot(multi_dimensional)
except Exception as e:
    print(e)

try:
    RMSE(multi_dimensional,len_4_a)
except Exception as e:
    print(e)

try:
    RMSE(len_4_b,len_4_a)
    print("RMSE ran succesfully")
except Exception as e:
    print(e)

try:
    RMSE(len_4_b,len_5)
except Exception as e:
    print(e)

Faulty input dimensions for L1
Faulty input dimensions for L2Dot
Faulty input dimensions for RMSE
RMSE ran succesfully
Faulty input dimensions for RMSE
